name: Performance Check
on:
  push:
    branches:
      - 'master'
    tags: '*'
  pull_request:
jobs:
  build-and-benchmark:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1']
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: ${{ matrix.julia-version }}
    - name: Build project
      uses: julia-actions/julia-buildpkg@latest
    - run: julia --threads=auto --project=./benchmark/CI-scripts ./benchmark/CI-scripts/runtests.jl ${{ github.event.pull_request.base.ref }}
